version: '3.8'
services:
  apache2:
    ports:
      - "8000:80"
    build: ./docker/apache2
    container_name: apache2
    volumes:
      - ./src:/var/www/html

  # db:
  #   image: postgres:12.3-alpine
  #   container_name: postgres
  #     - "5432:5432"
  #   environment:
  #     TZ: "Asia/Tokyo"
  #     LANG: ja_JP.utf8
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test
  #   volumes:
  #     - ./docker/db:/var/lib/psql
  #     - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
