version: '3.8'
services:
  # Developで試す場合 (Apache2)
  # <===  ↓↓↓　Develop環境用 ↓↓↓  ===>
  app:
    ports:
      - "8000:80"
    build: ./docker/app
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
  # <===  ↑↑↑ Develop環境用 ↑↑↑  ===>

  # 本番環境に導入する場合 (Nginx)
  # <===  ↓↓↓　本番環境用 ↓↓↓  ===>
  # php:
  #   container_name: php
  #   build: ./docker/php
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  # nginx:
  #   image: nginx
  #   ports:
  #     - 8000:80
  #   container_name: laravel_app
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  # <===  ↑↑↑ 本番環境用 ↑↑↑  ===>

  db:
    # image: mysql:5.7
    build: ./docker/db
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Ipoca
      MYSQL_USER: devuser
      MYSQL_PASSWORD: card1234
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/phpmyadmin/sessions:/sessions
